server:
  port: 8888

logging:
  level:
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/d1medeiros/config-repo
          timeout: 2
          refreshRate: 60

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest